spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/fin?serverTimezone=Asia/Seoul
    password: dlwodud821
  jpa:
    database: mysql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        hibernate:
          show-sql:true
