spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/fin?serverTimezone=Asia/Seoul
    password: dlwodud821
  jpa:
    database: mysql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  header: Authorization
  secret: MGNhYjZkMzZhNjhiNzc1M2YzNTY1MjJlNTEyOTA2NmY0MGU1OGNlOWJiMmRiZGY1ZGI3YjY0NzgxMzUzMjdmMzU1ZTJlY2U1YzM0ZmYzMzk0NmRjNjAxZjBjMTAxZjYyMDNmNGQ1MmQ3YmEzMGFhN2MyZDFjMjQyODczMTBmMDQ=
  token-validity-in-seconds: 86400